version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the React app...
      - npm run build  # Generates the 'build' folder

  post_build:
    commands:
      - echo Moving index.html and static files to the root directory
      - cp -r build/* build/  # Copy everything from the 'build' folder to /tmp/build
      - cp -r build/public/* build/  # Move files from build/public (i.e., index.html) to the root
      - cp -r build/static/* build/static/  # Move static assets (JS, CSS) to the root as well

artifacts:
  files:
    - '**/*'  # Ensure the entire flattened structure is included
  base-directory: 'build'  # Point to the temporary folder where everything is copied
