version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the React app...
      - npm run build  # Builds the React app and outputs to the 'build/' directory
      #- mv build/public/index.html build/  # Move index.html to the root of the build folder
  post_build:
    commands:
      - echo Build complete.

artifacts:
  files:
    - '**/*'  # Includes all files in the 'build/' directory
  base-directory: 'build'  # Specify the output directory for the build
