version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the React app...
      - npm run build  # Generates the 'build' folder

artifacts:
  files:
    - '**/*'  # Ensure the entire flattened structure is included
  base-directory: 'build'  # Point to the temporary folder where everything is copied
